import csv

def translate_csv(input_file, output_file):
    translation_dict = {
        'username': 'Matric Number',
        'name': 'Full Name',
        'points': 'Total Points',
        'External CCA': 'External CCA',
        'Dean\'s list': 'Dean\'s list ',
        'cmc': 'cmc',
        'aca': 'aca',
        'band': 'band',
        'rockfest': 'rockfest ',
        'choir': 'choir',
        'drama': 'drama',
        'edc': 'edc',
        'dp main comm': 'dp main comm',
        'dp finance': 'dp finance',
        'dp fr': 'dp fr',
        'dp pubs': 'dp pubs',
        'dp mkt': 'dp mkt',
        'dp logs': 'dp logs',
        'dp lights': 'dp lights',
        'dp sounds': 'dp sounds',
        'dp sets': 'dp sets',
        'dp sm': 'dp sm',
        'dp choreo': 'dp choreo',
        'dp cast': 'dp cast',
        'dp d1': 'dp d1',
        'dp d2': 'dp d2',
        'dp d3': 'dp d3',
        'dp d4': 'dp d4',
        'dp d5': 'dp d5',
        'dp d6': 'dp d6',
        'dp d7': 'dp d7',
        'dp dc': 'dp dc',
        'du afterdark': 'du afterdark',
        'du hot trio': 'du hot trio',
        'du smookin': 'du smookin',
        'expeds': 'expeds',
        'es': 'es',
        'minds': 'minds',
        'sa': 'sa',
        'green comm': 'green comm',
        'smc': 'smc',
        'badminton': 'badminton',
        'basketball': 'basketball',
        'floorball': 'floorball',
        'frisbee': 'frisbee',
        'handball': 'handball',
        'netball': 'netball',
        'road relay': 'road relay',
        'takraw': 'takraw',
        'football': 'football',
        'softball': 'softball',
        'squash': 'squash',
        'swim': 'swim',
        'table tennis': 'table tennis',
        'tennis': 'tennis',
        'trug': 'trug',
        'track': 'track',
        'volleyball': 'volleyball',
        'tm': 'tm',
        'a blk': 'a blk',
        'b blk': 'b blk',
        'c blk': 'c blk',
        'd blk': 'd blk',
        'e blk': 'e blk',
        'spt': 'spt',
        'hrb': 'hrb',
        'hpb': 'hpb ',
        'ew heads & logs': 'ew heads & logs',
        'ew photog': 'ew photog',
        'ew vid': 'ew vid ',
        'ew audio': 'ew audio ',
        'ew design': 'ew design',
        'ew dmm': 'ew dmm ',
        'ew logs': 'ew logs',
        'ew cro': 'ew cro ',
        'audit': 'audit',
        'elections': 'elections',
        'finance': 'finance',
        'hackers': 'hackers',
        'eer': 'eer',
        'ehoc': 'ehoc',
        'rag comm': 'rag comm',
        'rag dancer': 'rag dancer',
        'flag': 'flag '
    }

    with open(input_file, 'r', encoding="utf-8-sig") as csv_in, open(output_file, 'w', newline='') as csv_out:
        reader = csv.DictReader(csv_in)
        fieldnames = [
            'username',
            'name',
            'points',
            'External CCA',
            'Dean\'s list',
            'cmc',
            'aca',
            'band',
            'rockfest',
            'choir',
            'drama',
            'edc',
            'dp main comm',
            'dp finance',
            'dp fr',
            'dp pubs',
            'dp mkt',
            'dp logs',
            'dp lights',
            'dp sounds',
            'dp sets',
            'dp sm',
            'dp choreo',
            'dp cast',
            'dp d1',
            'dp d2',
            'dp d3',
            'dp d4',
            'dp d5',
            'dp d6',
            'dp d7',
            'dp dc',
            'du afterdark',
            'du hot trio',
            'du smookin',
            'expeds',
            'es',
            'minds',
            'sa',
            'green comm',
            'smc',
            'badminton',
            'basketball',
            'floorball',
            'frisbee',
            'handball',
            'netball',
            'road relay',
            'takraw',
            'football',
            'softball',
            'squash',
            'swim',
            'table tennis',
            'tennis',
            'trug',
            'track',
            'volleyball',
            'tm',
            'a blk',
            'b blk',
            'c blk',
            'd blk',
            'e blk',
            'spt',
            'hrb',
            'hpb',
            'ew heads & logs',
            'ew photog',
            'ew vid',
            'ew audio',
            'ew design',
            'ew dmm',
            'ew logs',
            'ew cro',
            'audit',
            'elections',
            'finance',
            'hackers',
            'eer',
            'ehoc',
            'rag comm',
            'rag dancer',
            'flag'
        ]
        writer = csv.DictWriter(csv_out, fieldnames=fieldnames)

        writer.writeheader()

        for row in reader:
              translated_row = {
                  field: row[translation_dict.get(field, field)] for field in fieldnames
              }
              writer.writerow(translated_row)
        # for row in reader:
        #     translated_row = {translation_dict.get(key, key): value for key, value in row.items()}
        #     writer.writerow(translated_row)

if __name__ == "__main__":
    input_file = "./csv/points_raw.csv"
    output_file = "./csv/points_formatted.csv"
    translate_csv(input_file, output_file)
